# Traefik static configuration
# This file contains static configuration that doesn't change often

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"
    http:
      tls: {}

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    watch: true
  
  file:
    directory: /etc/traefik/dynamic
    watch: true

# API and dashboard configuration
api:
  dashboard: true
  insecure: false

# Logging configuration
log:
  level: INFO

accessLog: {}

# Metrics configuration (optional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
