version: '3.8'

services:
  realtime-assistant:
    build: .
    container_name: realtime-assistant
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8888
      - CHAINLIT_PUBLIC_URL=${CHAINLIT_PUBLIC_URL:-http://localhost:8888}
    volumes: []
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 