version: '3.8'

services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    
    networks:
      - proxy
      - app-network
    
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard (optional)
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik:/etc/traefik
    
    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      
      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=admin@renovavision.tech"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      
      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
      
      # Observability
      - "--log.level=INFO"
      - "--accesslog=true"
    
    labels:
      - "traefik.enable=true"
      # Dashboard router (optional - comment out if not needed)
      - "traefik.http.routers.dashboard.rule=Host(`traefik.renovavision.tech`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"

  # Your realtime assistant app
  realtime-assistant:
    build: .
    container_name: realtime-assistant
    restart: unless-stopped
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8888
      - CHAINLIT_PUBLIC_URL=https://realtime-demo.renovavision.tech
    env_file:
      - .env
    networks:
      - app-network
    # Don't expose port 8888 to host in production
    # Traefik will handle external access
    expose:
      - "8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.realtime-assistant.rule=Host(`realtime-demo.renovavision.tech`)"
      - "traefik.http.routers.realtime-assistant.entrypoints=websecure"
      - "traefik.http.routers.realtime-assistant.tls=true"
      - "traefik.http.routers.realtime-assistant.tls.certresolver=le"
      - "traefik.http.services.realtime-assistant.loadbalancer.server.port=8888"

networks:
  proxy:
    external: true
  app-network:
    driver: bridge

volumes:
  letsencrypt:
    driver: local
